### ISSUE TITLE
I would like to create a dashboard in kibana with the alerts detected by snort in security onion?

### ISSUE THREAD

**Issue by joalbarracin** [dougburks/securityonion-elastic#156]
First of all, I congratulate you on the security onion project.
I'm new, and I do not understand how I should create a dashboard with snort alerts in kibana. I installed the new iso 14.04.5.13. I see the alerts that are generated by when I press play -> squert, but my dashboard in kibana does not present the graphics and cakes with the alerts that are detected by it. Show 0 and no graph.
I would like to create a dashboard similar to this link
https://blog.snort.org/2017/11/snort-30-with-elasticsearch-logstash.html
but with detections of malwares, virus etc ip destination ip origin with everything that is detected by snort or meerkat according to the rules enabled.

Sorry for the inconvenience and I would appreciate all the possible help indicating the steps to achieve it.
Thank you so much.

**Comment by dougburks** [comment]
Hi @joalbarracin ,

Please send all questions/problems to our security-onion mailing list:
https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists

Thanks!
